x-app_environment: &app_environment
  PROJECT_NAME: ${PROJECT_NAME:-api-gateway}
  DEBUG: ${DEBUG:-True}
  CORS_ORIGINS: ${CORS_ORIGINS:-*}
  LOGGING_SERIALIZER: ${LOGGING_SERIALIZER:-False}
  LOGGING_LEVEL: ${LOGGING_LEVEL:-INFO}

x-redis_environment: &redis_environment
  REDIS_HOST: ${REDIS_HOST:-redis}
  REDIS_PORT: ${REDIS_PORT:-6379}

x-elastic_environment: &elastic_environment
  ELASTIC_HOST: ${ELASTIC_HOST:-elastic}
  ELASTIC_PORT: ${ELASTIC_PORT:-9200}


services:
  app:
    container_name: gateway-app
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app/:cached
    ports:
      - 8080:8080
    entrypoint: docker/entrypoint.sh
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      - redis
    environment:
      <<: [*app_environment, *redis_environment, *elastic_environment]
    networks:
      - cinema-bridge

  redis:
    container_name: gateway-redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    volumes:
      - ./${REDIS_DATA:-redis-data}:/data
    ports:
      - 6379:6379
    networks:
      - cinema-bridge

networks:
  cinema-bridge:
    name: local-dev-network
    external: true