src = ["."]
target-version = "py310"

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "**/data/migrations/versions/**",
    "**/tests/**",
]

line-length = 100


[lint]

select = ["ALL"]
extend-select = ["I"]

# all ruff errors before it has been installed
ignore = [
    "ANN101",
    "ANN401",
    "ARG001",
    "ARG002",
    "TID252",
    "RUF001",
    "RUF002",
    "FBT001",
    "FBT002",
    "PT001",
    "PTH118",
    "PTH122",
    "S101",
    "A001",
    "A003",
    "D100",
    "D101",
    "D102",
    "D103",
    "D105",
    "D106",
    "D203",
    "D213",
    "D404",
    "EXE002",
    "COM812",
    "ERA001",
    "TCH001",
    "A002",
    "ANN001",
    "ANN102",
    "ANN201",
    "ANN204",
    "ARG004",
    "B008",
    "B904",
    "BLE001",
    "C401",
    "C408",
    "C416",
    "C901",
    "D104",
    "D107",
    "D205",
    "D400",
    "D401",
    "D402",
    "D415",
    "D417",
    "DTZ004",
    "DTZ005",
    "E402",
    "E501",
    "EM101",
    "EM102",
    "F401",
    "F841",
    "FIX002",
    "N805",
    "N818",
    "PERF203",
    "PERF401",
    "PGH003",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR2004",
    "PLW2901",
    "RET503",
    "RET504",
    "RET505",
    "RUF003",
    "RUF009",
    "RUF012",
    "S106",
    "SIM102",
    "TCH002",
    "TCH003",
    "TD002",
    "TD003",
    "TRY002",
    "TRY003",
    "TRY30",
]

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.mccabe]
max-complexity = 10
